language: java
jdk:
  - oraclejdk8
script: 
- for mod in cadc-web-util cadc-web-test ; do cd $mod; gradle --info javadoc build install || break -1; cd ..; done

# - for i in cadc-web-util cadc-web-test ; do
#      cd $i;
#      gradle checkstyleMain || break -1;
#      cd ..;
#   done
